config/routes.rb
Rails.application.routes.draw do
  root 'deal_categories#index'

  resources :deal_categories, only: %i(index show)

  namespace :home do
    get 'how_to'
    get 'about'
  end
end

app/models/input_endpoint.rb
class InputEndpoint < XapixClient::Resource
end

app/models/local_deal.rb
class LocalDeal < XapixClient::Resource
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/deal_categories_controller.rb
class DealCategoriesController < ApplicationController

  after_action :log_errors, only: %i(index show), if: ->() { @deals.has_errors? }

  def index
    @deals = LocalDeal.order(:score).page(1).per(15)
  end

  def show
    @parameters = params.slice(:id, :local_deals, :page, :controller, :action).reject { |_k, v| v.blank? }
    current_page = @parameters.key?(:page) ? @parameters[:page].to_i : 1
    @deals = LocalDeal.where(category: @parameters[:id]).order(:score).page(current_page).per(30)
    if @parameters.key?(:local_deals) && @parameters[:local_deals][:market].present?
      @parameters[:local_deals][:market].downcase!
      @deals.where(market: @parameters[:local_deals][:market])
    end
  end

  private

  def log_errors
    @deals.errors.each { |error| Rails.logger.warn "XAPIX error: '#{error.status} - #{error.title}'" }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/deal_categories/index.html.haml
%section.portfolio
  .container
    .row
      .col-xs-12.col-sm-6.col-md-4
        %article.block-thumbnail
          %a.block-thumb{:href => deal_category_path('travel')}
            .block-image
              .overlay
                .icon
                  = fa_icon 'bars'
              = image_tag	'travel_square.jpg', alt: 'Travel. Artist: Nico Trinkhaus @ sumfinity.com'
          .block-data
            %h3= link_to t("deal_categories.index.travel_deals"), deal_category_path('travel')
            %span.block-category= t("deal_categories.index.save_on_hotels_and_getaways")
      .col-xs-12.col-sm-6.col-md-4
        %article.block-thumbnail
          %a.block-thumb{:href => deal_category_path('wellness')}
            .block-image
              .overlay
                .icon
                  = fa_icon 'bars'
              = image_tag	'wellness_square.jpg', alt: 'Wellness. Artist: powerstock @ fotolia.com'
          .block-data
            %h3= link_to t("deal_categories.index.wellness_deals"), deal_category_path('wellness')
            %span.block-category= t("deal_categories.index.save_on_spa_and_wellness")
      .col-xs-12.col-sm-6.col-md-4
        %article.block-thumbnail
          %a.block-thumb{:href => deal_category_path('activities')}
            .block-image
              .overlay
                .icon
                  = fa_icon 'bars'
              = image_tag	'activities_square.jpg', alt: 'Activities. Artist: Halfpoint @ fotolia.com'
          .block-data
            %h3= link_to t("deal_categories.index.activity_deals"), deal_category_path('activities')
            %span.block-category= t("deal_categories.index.save_on_gastronomy_action_and_events")

%section.calltoaction.intro
  .container
    .row
      .col-md-12.text-center
        .intro-content
          %h1
            = t("slogan.leisure_deals_most")
            %strong= t("slogan.relaxed")
            = t("slogan.deals")
          %h2= t("slogan.we_have_the_best_savings_on_leisure_deals_out_there")
    .row
      = form_tag root_path, id: 'contactform' do
        %fieldset
          .col-md-2
          %label{:accesskey => "E", :for => "email"}
          = text_field_tag 'email', '', placeholder: t('deal_categories.index.email_placeholder'), class: 'email col-md-6 cta-field cta-email-field'
          = submit_tag t("deal_categories.index.sign_up"), class: 'btn btn-border submit col-md-2'
          .col-md-2
            
%section
  .container
    .row
      .col-md-12.text-center
        .intro-content
          %h1= t("deal_categories.index.todays_top_deals")
    
    - if @deals.errors.any?
      = render partial: '/shared/no_deals_error'
    - else
      - @deals.in_groups_of(3).each do |deals|
        .row
          - deals.compact.each do |deal|
            = render partial: '/shared/deal', locals: { deal: deal }

app/views/deal_categories/show.html.haml
%section.portfolio
  .container
    .row
      .col-md-12
        %article.block-thumbnail
          %a.block-thumb{:href => root_path}
            .block-image
              .overlay
                .icon
                  = fa_icon 'backward'
              = image_tag "#{@parameters[:id]}_wide.jpg"
          .block-data
            %h3= link_to t('deal_categories.show.deals_best_savings', category: t("layouts.application.#{@parameters[:id]}")), '#'

%section
  .container
    - if @deals.errors.any?
      = render partial: '/shared/no_deals_error'
    - else
      .row.calltoaction
        .pagination-links.col-sm-6{style: 'text-align: left'}
          %p
            = link_to '<<', @parameters.merge(page: @deals.meta['pagination']['first']), class: 'btn btn-border'
            - if @deals.meta['pagination']['prev'].present?
              = link_to '<', @parameters.merge(page: @deals.meta['pagination']['prev']), class: 'btn btn-border'
            %a.btn.btn-border{href: '#'}== #{@deals.meta['pagination']['current'] } / #{@deals.meta['pagination']['last']}
            - if @deals.meta['pagination']['next'].present?
              = link_to '>', @parameters.merge(page: @deals.meta['pagination']['next']), class: 'btn btn-border'
            = link_to '>>', @parameters.merge(page: @deals.meta['pagination']['last']), class: 'btn btn-border'
        
        = form_tag(deal_category_path(@parameters[:id]), :method => "get", class: 'col-sm-6') do
          %fieldset.pull-right.form-group
            = select :local_deals, :market, options_for_select([%w(Deutschland de), %w(Österreich at), %w(Schweiz ch)], @parameters[:market]), { prompt: 'Markt wählen...' }, { class: 'cta-field' }
            = submit_tag "Go", class: 'btn btn-border cta-email-submit'

      - @deals.in_groups_of(3).each do |deals|
        .row
          - deals.compact.each do |deal|
            = render partial: '/shared/deal', locals: { deal: deal }

app/views/home/about.html.haml
%a{name: 'who-we-are'}
%section.intro
  .container
    .row
      .col-md-12.text-center
        %a.navbar-brand{href: root_path, style: 'float: none;'}
          = fa_icon('ticket')
          %span= t("leisure_deals")
    .row
      .col-md-12.text-center
        .intro-content
          %h1
            = t("slogan.leisure_deals_most")
            %strong= t("slogan.relaxed")
            = t("slogan.deals")
          %h2= t("slogan.we_have_the_best_savings_on_leisure_deals_out_there")

%section.aboutme
  .container
    .row
      .col-xs-6.col-sm-6.col-md-3.text-center
        %h4= link_to image_tag('svenja_brau.jpg', alt: 'Svenja Brau', class: 'col-md-12'), 'https://de.linkedin.com/pub/svenja-brau/4a/a45/841/de'
        %p
          %strong= t("home.about.who_we_are_project_manager")
        %p= t("home.about.who_we_are_svenja")
      .col-xs-6.col-sm-6.col-md-3.text-center
        %p= link_to image_tag('oliver_thamm.jpg', alt: 'Oliver Thamm', class: 'col-md-12'), 'https://de.linkedin.com/pub/oliver-thamm/72/74b/384'
        %p
          %strong= t("home.about.who_we_are_software_engineer")
        %p= t("home.about.who_we_are_oliver")
      .col-xs-12.col-sm-12.col-md-6
        %h3= t("home.about.our_mission")
        %p
          %strong= t("home.about.our_mission_content")

%a{name: 'impressum'}
%section.content
  .container
    .row
      .col-xs-12.col-sm-12.col-md-6
        %h2= t("home.about.impressum")
        %h3= t("home.about.our_office_in_berlin_germany")
        %p
          Pickled Olives Software
          %br
          Heinersdorfer Str. 39
          %br
          13086 Berlin, (GER)
        %a.btn.btn-border{:href => 'mailto:office@pickled-olives.com'}
          %i.fa.fa-envelope-o
          Email
      .col-xs-12.col-sm-12.col-md-6
        = image_tag 'https://maps.googleapis.com/maps/api/staticmap?center=Berlin,Germany&zoom=11&size=600x300&maptype=roadmap&markers=52.55547,13.43169'

app/views/home/how_to.html.haml
%section.blog
  .container
    .row

      %a{name: 'how-it-works'}
      .col-xs-12.col-sm-12.col-md-9
        %article.blog-post
          .blogtitle
            %h1= t("home.how_to.how_leisure_deals_works")
          .blogcontent

            %a{name: 'what-we-do'}
            %h3= t("home.how_to.what_we_do")
            %p= t("home.how_to.what_we_do_content")
            %ul
              %li= t('home.how_to.what_we_do_1')
              %li= t('home.how_to.what_we_do_2')
              %li= t('home.how_to.what_we_do_3')

            %a{name: 'how-we-do-it'}
            %h3= t("home.how_to.how_we_do_it")
            %p= t("home.how_to.how_we_do_it_content")

      .col-xs-12.col-sm-12.col-md-3
        .sidebar
          .col-xs-12.col-sm-6.col-md-12.sidebar-item
            %span.name= t("home.how_to.how_it_works")
            %ul.links
              %li
                %a{:href => "#what-we-do"}= t("home.how_to.what_we_do")
              %li
                %a{:href => "#how-we-do-it"}= t("home.how_to.how_we_do_it")
          .col-xs-12.col-sm-6.col-md-12.sidebar-item
            %span.name= t("home.how_to.partners")
            %ul.links
              %li
                %a{:href => "#groupon"}= t("home.how_to.groupon")
          .col-xs-12.col-sm-6.col-md-12.sidebar-item
            %span.name= t("home.how_to.our_values")
            %ul.links
              %li
                %a{:href => "#security"}= t("home.how_to.security")
              %li
                %a{:href => "#privacy"}= t("home.how_to.privacy")
              %li
                %a{:href => "#transparency"}= t("home.how_to.transparency")
          .col-xs-12.col-sm-6.col-md-12.sidebar-item
            %span.name= t("home.how_to.tos_short")
            %ul.links
              %li
                %a{:href => "#terms-of-service"}= t("home.how_to.tos")

      %a{name: 'partners'}
      .col-xs-12.col-sm-12.col-md-9
        %article.blog-post
          .blogtitle
            %h1= t("home.how_to.partners")
        .comments
          %ul
            %a{name: 'groupon'}
            %li.single-comment
              .author-image{style: 'width: 80px;'}
                = image_tag 'groupon_400x400.png', size: '80x80'
              .author-data
                %strong= t("home.how_to.groupon")
              .author-text
                %p= t("home.how_to.groupon_content")
              %ul.children
                %li.single-comment
                  .author-image
                    %a{href: "http://ad.zanox.com/ppc/?27443407C1647186729T",  target: "_blank"}
                      %img{src: "http://ad.zanox.com/ppv/?27443407C1647186729", align: "bottom", width: "120", height: "60", border: "0", hspace: "1", alt: "CityDeal - Deine Stadt zum halben Preis!"}
                  .author-data
                    = link_to t("home.how_to.groupon_de"), 'http://ad.zanox.com/ppc/?27443407C1647186729T', class: 'reply'
                  .author-text
                    %p= t("home.how_to.groupon_de_content")
                %li.single-comment
                  .author-image
                    %a{href: "http://ad.zanox.com/ppc/?27989075C525867590T",  target: "_blank"}
                      %img{src: "http://ad.zanox.com/ppv/?27989075C525867590", align: "bottom", width: "120", height: "60", border: "0", hspace: "1", alt: "CityDeal - Deine Stadt zum halben Preis!"}
                  .author-data
                    = link_to t("home.how_to.groupon_ch"), 'http://ad.zanox.com/ppc/?27989075C525867590T', class: 'reply'
                  .author-text
                    %p= t("home.how_to.groupon_ch_content")
                %li.single-comment
                  .author-image
                    %a{href: "http://ad.zanox.com/ppc/?27989110C1770725866T",  target: "_blank"}
                      %img{src: "http://ad.zanox.com/ppv/?27989110C1770725866", align: "bottom", width: "120", height: "60", border: "0", hspace: "1", alt: "CityDeal - Deine Stadt zum halben Preis!"}
                  .author-data
                    = link_to t("home.how_to.groupon_at"), 'http://ad.zanox.com/ppc/?27989110C1770725866T', class: 'reply'
                  .author-text
                    %p= t("home.how_to.groupon_at_content")
      
      %a{name: 'our-values'}
      .col-xs-12.col-sm-12.col-md-9
        %article.blog-post
          .blogtitle
            %h1= t("home.how_to.our_values")
          .blogcontent

            %a{name: 'security'}
            %h3= t("home.how_to.security")
            %p= t("home.how_to.security_content")

            %a{name: 'privacy'}
            %h3= t("home.how_to.privacy")
            %p= t("home.how_to.privacy_content")

            %a{name: 'transparency'}
            %h3= t("home.how_to.transparency")
            %p= t("home.how_to.transparency_content")

      %a{name: 'terms-of-service'}
      .col-xs-12.col-sm-12.col-md-9
        %article.blog-post
          .blogtitle
            %h1== #{t("home.how_to.tos_short")} - #{t("home.how_to.tos")}
          .blogcontent
            %p= t("home.how_to.tos_content")
            %p= t("home.how_to.tos_version")
            %p= t("home.how_to.tos_accept")

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    
    %link{href: 'http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700', rel: 'stylesheet', type: 'text/css'}

    %title= content_for?(:title) ? yield(:title) : t('leisure_deals')
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"

    = stylesheet_link_tag "application", :media => "all", "data-turbolinks-track" => false
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'


  %body{class: ('sticky-header' if controller_name == 'deal_categories')}

    %header.header
      %nav.navbar.navbar-default{role: 'navigation', class: ('navbar-sticky' if controller_name == 'deal_categories')}
        .container
          .row
            .col-md-12
              .navbar-header
                %a.navbar-brand{href: root_path}
                  = fa_icon('ticket')
                  %span= t("leisure_deals")

              .navbar-collapse.collapse
                %ul.nav.nav-pills.nav-main.pull-right
                  %li.dropdown{class: ('active' if controller_name == 'deal_categories')}
                    = link_to t("layouts.application.categories"), '#', class: 'dropdown-toggle', data: { 'toggle' => 'dropdown' }
                    %ul.dropdown-menu
                      %li= link_to t("layouts.application.travel"), deal_category_path('travel')
                      %li= link_to t("layouts.application.wellness"), deal_category_path('wellness')
                      %li= link_to t("layouts.application.activities"), deal_category_path('activities')
                  
                  %li.dropdown{class: ('active' if action_name == 'how_to')}
                    = link_to t("layouts.application.how_it_works"), home_how_to_path, class: 'dropdown-toggle', data: { 'toggle' => 'dropdown' }
                    %ul.dropdown-menu
                      %li= link_to t("layouts.application.description"), home_how_to_path(anchor: 'how-it-works')
                      %li= link_to t("home.how_to.partners"), home_how_to_path(anchor: 'partners')
                      %li= link_to t("home.how_to.our_values"), home_how_to_path(anchor: 'our-values')
                      %li= link_to t("home.how_to.tos_short"), home_how_to_path(anchor: 'terms-of-service')
                  
                  %li.dropdown{class: ('active' if action_name == 'about')}
                    = link_to t("layouts.application.about"), home_about_path, class: 'dropdown-toggle', data: { 'toggle' => 'dropdown' }
                    %ul.dropdown-menu
                      %li= link_to t("layouts.application.about_us"), home_about_path(anchor: 'who-we-are')
                      %li= link_to t("layouts.application.impressum"), home_about_path(anchor: 'impressum')
                  
                  %li= mail_to 'office@pickled-olives.com', t('layouts.application.contact')

    %section.flash-errors
      .container
        .row
          .col-lg-12
            = bootstrap_flash
    
    = yield

    %footer.footer
      .container
        .row
          .col-md-4
            .footeritem
              %h4= t("layouts.application.deal_categories")
              %ul.popular-posts
                %li= link_to t("layouts.application.travel"), deal_category_path('travel')
                %li= link_to t("layouts.application.wellness"), deal_category_path('wellness')
                %li= link_to t("layouts.application.activities"), deal_category_path('activities')
          .col-xs-12.col-sm-6.col-md-4
            .footeritem
              %h4= t("layouts.application.keep_updated")
              %p= t("layouts.application.keep_updated_content")
              %form#contactform{:action => "#", :method => "post", :name => "contactform"}
                %fieldset
                  %label{:accesskey => "E", :for => "email"}
                  %input#email.email{:name => "email", :placeholder => t('layouts.application.email_placeholder'), :size => "30", :type => "text", :value => ""}/
                  %button#submit.btn.btn-border.submit{:type => "submit", :value => "submit"}
                    %i.fa.fa-rocket
                    = t("layouts.application.send")
              #message
          .col-xs-12.col-sm-6.col-md-4
            .footeritem
              %h4= t("layouts.application.visit_us_on_facebook")
              %p= t("layouts.application.keep_track_content")
              %a.btn.btn-border{:href => "#"}= t("layouts.application.visit_facebook")
    
    %a.scrollToTop{:href => "#"}
      %i.fa.fa-angle-up

    %footer.footer
      .container
        .row
          .col-lg-10
            %p
              &copy; Pickled Olives Software 2015. leisuredeals.net is Proud Beta Test Partner of
              = link_to 'www.xapix.io', 'http://www.xapix.io'
              !
          .col-lg-1
            %p= link_to t("home.how_to.tos_short"), home_how_to_path(anchor: 'terms-of-service')
          .col-lg-1
            %p= link_to t("home.about.impressum"), home_about_path(anchor: 'impressum')
                

    = javascript_include_tag 'application', "data-turbolinks-track" => false
    = yield(:page_javascript) if content_for?(:page_javascript)

app/views/shared/_deal.html.haml
.col-xs-12.col-sm-6.col-md-4
  %article.block-thumbnail
    %a.block-thumb{:href => deal.link_url}
      .block-image
        .overlay
          .icon= fa_icon 'cart-plus'
        = image_tag deal.image_url
    .block-data
      %h3{style: 'font-size: 24px;'}
        %a{:href => deal.link_url}= deal.title
      %span.block-category= deal.description

app/views/shared/_no_deals_error.html.haml
.row
  .col-md-12.text-center
    %p
      %h2 We are sorry, due to technical problems we cannot retrieve deals at the moment.
    %br 